# Generated by Django 5.2.3 on 2025-06-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='defeat',
            field=models.IntegerField(default=0, verbose_name='Defeat Counter'),
        ),
        migrations.AddField(
            model_name='deck',
            name='win',
            field=models.IntegerField(default=0, verbose_name='Win Counter'),
        ),
        migrations.AddField(
            model_name='player',
            name='defeat',
            field=models.IntegerField(default=0, verbose_name='Defeat Counter'),
        ),
        migrations.AddField(
            model_name='player',
            name='win',
            field=models.IntegerField(default=0, verbose_name='Win Counter'),
        ),
    ]
