# Generated by Django 5.2.3 on 2025-06-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_deck_defeat_deck_win_player_defeat_player_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player',
        ),
        migrations.AddField(
            model_name='match',
            name='participants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
