# Generated by Django 5.2.3 on 2025-06-22 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_match_deck_remove_match_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='participants',
        ),
        migrations.AddField(
            model_name='match',
            name='deck',
            field=models.ManyToManyField(related_name='match_deck', to='home.deck', verbose_name='Decks'),
        ),
        migrations.AddField(
            model_name='match',
            name='player',
            field=models.ManyToManyField(related_name='match_players', to=settings.AUTH_USER_MODEL, verbose_name='Paticipants'),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Player Username'),
        ),
    ]
