# Generated by Django 5.2.3 on 2025-06-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_match_participants_match_deck_match_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='image',
            field=models.ImageField(upload_to='img/decks/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(upload_to='img/players', verbose_name='Player Image'),
        ),
    ]
