# Generated by Django 5.2.3 on 2025-06-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_deck_image_alter_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='image',
            field=models.TextField(),
        ),
    ]
