# Generated by Django 5.2.3 on 2025-06-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_deck_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='image',
            field=models.BinaryField(),
        ),
    ]
