# Generated by Django 5.2.3 on 2025-06-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_deck_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='image_type',
            field=models.CharField(default='data:image/webp;base64', max_length=100),
        ),
    ]
