# Generated by Django 5.2.3 on 2025-06-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_deck_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrizione Giocatore'),
        ),
    ]
